/**
 * svgIllustrationEngine.ts — Avelut Realistic AI-Generated SVG Illustration System
 *
 * Provides deep domain prompting, validation, sanitization, defs injection,
 * and chalkboard drawing animations for realistic vector illustrations generated by LLMs from scratch.
 */

import katex from 'katex';

/**
 * Dedicated System Prompt instructing the LLM to generate rich, realistic, recognizable
 * vector illustrations from scratch with accurate scientific annotations.
 */
export const SVG_REALISTIC_ILLUSTRATION_SYSTEM_PROMPT = `
================================================================================
AVELUT REALISTIC VECTOR ILLUSTRATION SYSTEM (CHALKBOARD STEM SVG ENGINE)
================================================================================
When generating a visual illustration (diagramSvg), you must draw a COMPLETE, REALISTIC, HIGHLY RECOGNIZABLE vector illustration from scratch in valid SVG.

CORE MANDATE: REAL RECOGNIZABLE OBJECTS — NEVER PRIMITIVE PLACEHOLDER SHAPES
- If the concept involves a CAR: Draw an actual recognizable car (chassis contours, windshield with reflection, side windows, wheels with rims and tires, headlights with beam cones, road with perspective). NEVER draw a generic rectangle with two circles!
- If the concept involves a BICYCLE: Draw an actual recognizable bicycle (tubular diamond frame, front fork, handlebars with grips, spoked wheels, chain, pedals, saddle).
- If the concept involves a HEART: Draw an anatomical heart (aorta arch with 3 branching arteries, pulmonary artery and veins, superior/inferior vena cava, right/left atria and ventricles, muscle wall cross-section, oxygenated/deoxygenated blood flow arrows).
- If the concept involves a CIRCUIT: Draw recognizable realistic components (cylindrical 3D battery with positive terminal knob, light bulb with visible tungsten spiral filament and glass dome, knife switch with open/closed contact blade, color-coded 4-band resistor cylinder).
- If the concept involves OPTICS / REFRACTION: Draw a recognizable 3D biconvex/concave glass lens with thickness and transparent glass gradient, incident and refracted light beams, surface normal dashed lines, and labeled angle arcs $\\theta_1, \\theta_2$.
- If the concept involves a PULLEY / SPRING: Draw a realistic grooved pulley wheel with central axle bracket, multi-strand taut rope, or a realistic 3D coiled spring with shaded helical loops and hanging mass with weight label.
- If the concept involves a CELL / BIOLOGY: Draw phospholipid bilayer membrane, nucleus with double membrane and chromatin, folded endoplasmic reticulum with ribosomes, mitochondria with inner cristae folds.
- If the concept involves CHEMISTRY / LAB: Draw volumetric Erlenmeyer flask or beaker with measurement graduation ticks, liquid meniscus with surface reflection, Bunsen burner with blue inner and outer flame cones, bubble particles for reactions.
- If the concept involves MATHEMATICS: Draw crisp coordinate axes with numbered graduation ticks, smooth Bézier curves, colored area integrals, geometric shapes with right-angle markers, dimension arrows, and angle arcs $\\theta$.

CANVAS & VIEWBOX SPECIFICATIONS:
- Root element: <svg viewBox="0 0 800 480" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid meet">
- Optimized for Dark Charcoal Blackboard (#12161A / #181C20).
- Use high-contrast, harmonious educational palette:
  * Primary Structures & Objects: #38BDF8 (Sky Blue), #F8FAFC (Chalk White), #CBD5E1 (Slate Silver), #E2E8F0
  * Velocity & Target Quantities: #34D399 (Emerald Green), #10B981
  * Forces, Friction & Resistance: #F87171 (Coral Red), #EF4444
  * Givens, Dimensions & Angles: #FBBF24 (Amber Gold), #F59E0B
  * Field Lines, Waves & Potentials: #A78BFA (Violet Purple), #818CF8
  * Glass & Translucent Media: fill="url(#grad-glass)" or opacity="0.35"
  * Metallic & Body Gradients: fill="url(#grad-sky-glow)", fill="url(#grad-metal)", fill="url(#grad-amber-glow)"

VECTOR ARROWS & ANNOTATIONS:
- All force and vector arrows must use: marker-end="url(#arrow-sky)", marker-end="url(#arrow-green)", marker-end="url(#arrow-red)", marker-end="url(#arrow-amber)", or marker-end="url(#arrow-purple)".
- Format math labels in standard LaTeX notation ($F_{\\\\text{net}}$, $v_f$, $a$, $\\\\theta$, $m$, $g$) or clear crisp typography.
- Group elements with semantic classes to enable progressive chalkboard drawing animation:
  * class="chalk-scene-bg" for ground, axes, background scenery.
  * class="chalk-main-object" for the primary physical body (car, bicycle, heart, beaker, lens).
  * class="chalk-object-details" for internal textures, spokes, filaments, cell organelles, graduation marks.
  * class="chalk-vectors" for force arrows, velocity vectors, ray paths, dimension lines.
  * class="chalk-labels" for text callouts, LaTeX variable tags, and degree angles.
`;

/**
 * Standard definitions injected into every sanitized SVG:
 * - High-precision multi-color arrow markers
 * - Surface, depth, glass, and glow gradients
 * - Drop shadows and chalk bloom filters
 * - Scoped progressive blackboard drawing animations
 */
const INJECTED_SVG_DEFS = `
  <defs>
    <!-- Arrowhead Markers -->
    <marker id="arrow" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#E2E8F0" />
    </marker>
    <marker id="arrow-sky" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#38BDF8" />
    </marker>
    <marker id="arrow-blue" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#38BDF8" />
    </marker>
    <marker id="arrow-green" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#34D399" />
    </marker>
    <marker id="arrow-red" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#F87171" />
    </marker>
    <marker id="arrow-amber" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#FBBF24" />
    </marker>
    <marker id="arrow-purple" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#A78BFA" />
    </marker>
    <marker id="arrow-white" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#F8FAFC" />
    </marker>

    <!-- Gradients for Real Objects -->
    <linearGradient id="grad-glass" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#38BDF8" stop-opacity="0.4" />
      <stop offset="50%" stop-color="#0284C7" stop-opacity="0.15" />
      <stop offset="100%" stop-color="#38BDF8" stop-opacity="0.3" />
    </linearGradient>

    <linearGradient id="grad-sky-glow" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#38BDF8" stop-opacity="0.85" />
      <stop offset="100%" stop-color="#0369A1" stop-opacity="0.4" />
    </linearGradient>

    <linearGradient id="grad-metal" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" stop-color="#475569" />
      <stop offset="50%" stop-color="#94A3B8" />
      <stop offset="100%" stop-color="#334155" />
    </linearGradient>

    <linearGradient id="grad-amber-glow" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#FDE68A" />
      <stop offset="100%" stop-color="#D97706" />
    </linearGradient>

    <linearGradient id="grad-emerald-glow" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#6EE7B7" />
      <stop offset="100%" stop-color="#059669" />
    </linearGradient>

    <linearGradient id="grad-coral-glow" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#FCA5A5" />
      <stop offset="100%" stop-color="#DC2626" />
    </linearGradient>

    <linearGradient id="grad-purple-glow" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#C4B5FD" />
      <stop offset="100%" stop-color="#7C3AED" />
    </linearGradient>

    <radialGradient id="grad-radial-glow" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="#38BDF8" stop-opacity="0.35" />
      <stop offset="100%" stop-color="#0F172A" stop-opacity="0" />
    </radialGradient>

    <!-- Filters -->
    <filter id="chalk-glow" x="-20%" y="-20%" width="140%" height="140%">
      <feGaussianBlur stdDeviation="2.5" result="blur" />
      <feComposite in="SourceGraphic" in2="blur" operator="over" />
    </filter>

    <filter id="subtle-shadow" x="-10%" y="-10%" width="120%" height="120%">
      <feDropShadow dx="0" dy="4" stdDeviation="6" flood-color="#000000" flood-opacity="0.6" />
    </filter>

    <!-- Scoped Drawing Animation Styles -->
    <style>
      @keyframes chalkDraw {
        0% { stroke-dashoffset: 1200; opacity: 0.1; }
        100% { stroke-dashoffset: 0; opacity: 1; }
      }
      @keyframes chalkFade {
        0% { opacity: 0; transform: translateY(3px); }
        100% { opacity: 1; transform: translateY(0); }
      }
      @keyframes chalkPulse {
        0%, 100% { opacity: 0.85; filter: drop-shadow(0 0 2px rgba(56,189,248,0.4)); }
        50% { opacity: 1; filter: drop-shadow(0 0 8px rgba(56,189,248,0.9)); }
      }

      .chalk-scene-bg {
        animation: chalkFade 0.6s ease-out 0.1s both;
      }
      .chalk-main-object {
        animation: chalkFade 0.8s ease-out 0.3s both;
      }
      .chalk-object-details {
        animation: chalkFade 0.8s ease-out 0.6s both;
      }
      .chalk-vectors {
        animation: chalkFade 0.7s ease-out 0.9s both;
      }
      .chalk-labels {
        animation: chalkFade 0.6s ease-out 1.2s both;
      }
      .chalk-highlight {
        animation: chalkPulse 3s infinite ease-in-out 1.5s both;
      }

      svg text {
        font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
        user-select: none;
      }
    </style>
  </defs>
`;

/**
 * Parses and renders LaTeX expressions inside SVG text elements using KaTeX.
 */
function renderKatexInSvg(svgContent: string): string {
    return svgContent.replace(/<text([^>]*)>([\s\S]*?)<\/text>/gi, (fullMatch, attrs, rawInner) => {
        let content = rawInner.trim();
        if (!content.includes('$') && !content.includes('\\')) {
            return fullMatch;
        }

        const getAttr = (name: string, fallback = '') => {
            const m = attrs.match(new RegExp(`${name}="([^"]*)"`, 'i'));
            return m ? m[1] : fallback;
        };

        const x = parseFloat(getAttr('x', '0')) || 0;
        const y = parseFloat(getAttr('y', '0')) || 0;
        const fill = getAttr('fill', '#F8FAFC');
        const fontSize = getAttr('font-size', '13px');
        const textAnchor = getAttr('text-anchor', 'start').toLowerCase();
        const fontWeight = getAttr('font-weight', '600');

        let formattedHtml = content;
        try {
            formattedHtml = content.replace(/\$\$([\s\S]*?)\$\$/g, (_m: string, math: string) => {
                return katex.renderToString(math.trim(), { displayMode: false, throwOnError: false });
            });
            formattedHtml = formattedHtml.replace(/\$([^\$\n]+?)\$/g, (_m: string, math: string) => {
                return katex.renderToString(math.trim(), { displayMode: false, throwOnError: false });
            });
        } catch {
            return fullMatch;
        }

        let foWidth = 220;
        let foHeight = 44;
        let foX = x;
        let foY = y - 18;
        let justify = 'flex-start';
        let textAlign = 'left';

        if (textAnchor === 'middle') {
            foX = x - (foWidth / 2);
            justify = 'center';
            textAlign = 'center';
        } else if (textAnchor === 'end') {
            foX = x - foWidth;
            justify = 'flex-end';
            textAlign = 'right';
        }

        return `<foreignObject x="${foX}" y="${foY}" width="${foWidth}" height="${foHeight}" overflow="visible">
  <div xmlns="http://www.w3.org/1999/xhtml" style="color: ${fill}; font-size: ${fontSize}; font-family: ui-sans-serif, system-ui, -apple-system, sans-serif; font-weight: ${fontWeight}; display: flex; align-items: center; justify-content: ${justify}; text-align: ${textAlign}; width: 100%; height: 100%; pointer-events: none; line-height: 1.15;">
    ${formattedHtml}
  </div>
</foreignObject>`;
    });
}

/**
 * Validates, repairs, and sanitizes generated SVGs for safe, high-fidelity rendering.
 * - Strips dangerous scripts, event handlers, and external URLs
 * - Auto-repairs missing viewBox or closing tags
 * - Injects standard markers, gradients, and drawing animation styles
 * - Replaces LaTeX math tags with KaTeX typography
 */
export function sanitizeAndValidateSvg(rawSvg: string | null | undefined): string | null {
    if (!rawSvg || typeof rawSvg !== 'string') return null;

    let cleaned = rawSvg.trim();

    // 1. Strip markdown code block wrappers (```xml ... ``` or ```svg ... ```)
    cleaned = cleaned.replace(/^```(?:xml|svg|html)?\s*/i, '').replace(/```$/i, '').trim();

    // 2. Extract root <svg> ... </svg>
    const match = cleaned.match(/<svg[\s\S]*?<\/svg>/i);
    if (match) {
        cleaned = match[0];
    } else {
        // Attempt repair if closing tag was truncated
        const openMatch = cleaned.match(/<svg[\s\S]*/i);
        if (openMatch) {
            cleaned = `${openMatch[0]}</svg>`;
        } else {
            return null;
        }
    }

    // 3. Strip unsafe elements: <script>, <iframe>, <object>, <embed>, <applet>, <form>, <input>
    cleaned = cleaned.replace(/<\/?(?:script|iframe|object|embed|applet|form|input|meta|link)[^>]*>/gi, '');

    // 4. Strip unsafe attributes: on*, javascript:, data: (except safe images)
    cleaned = cleaned.replace(/\s+on\w+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi, '');
    cleaned = cleaned.replace(/href\s*=\s*["']\s*(?:javascript|vbscript):[^"']*["']/gi, 'href="#"');
    cleaned = cleaned.replace(/src\s*=\s*["']\s*(?:javascript|vbscript):[^"']*["']/gi, 'src=""');

    // 5. Ensure root attributes: viewBox, xmlns, width, height, preserveAspectRatio
    if (!cleaned.includes('viewBox')) {
        cleaned = cleaned.replace(/<svg/i, '<svg viewBox="0 0 800 480"');
    }
    if (!cleaned.includes('xmlns=')) {
        cleaned = cleaned.replace(/<svg/i, '<svg xmlns="http://www.w3.org/2000/svg"');
    }
    if (!cleaned.includes('preserveAspectRatio')) {
        cleaned = cleaned.replace(/<svg/i, '<svg preserveAspectRatio="xMidYMid meet"');
    }

    // 6. Inject standard defs & animation styles
    if (cleaned.includes('<defs>')) {
        cleaned = cleaned.replace(/<defs>/i, `<defs>${INJECTED_SVG_DEFS.replace('<defs>', '').replace('</defs>', '')}`);
    } else {
        cleaned = cleaned.replace(/<svg([^>]*)>/i, `<svg$1>${INJECTED_SVG_DEFS}`);
    }

    // 7. Render KaTeX math in text elements
    cleaned = renderKatexInSvg(cleaned);

    return cleaned;
}
