/**
 * Teaching Engine Service
 * - Generates TeachingScript segments
 * - Gates board actions until voice actually starts
 * - Syncs actions to audio progress when possible
 */

import { TeachingSegment, BoardAction, StudentAnswerEvaluation } from '../types/teachingScript';
import { TEACHING_DIRECTOR_SYSTEM_PROMPT, buildLessonSegmentPrompt, buildStudentAnswerEvaluationPrompt } from './teachingEnginePrompt';
import { createAvelutAI, getResponseText } from '../utils/inference';
import { unifiedVoiceRouter } from './voice/UnifiedVoiceRouter';
import { AppSettings, UserProfile } from '../types';

export interface TeachingEngineListener {
  onSegmentLoaded?: (segment: TeachingSegment) => void;
  onSpokenWord?: (word: string, phraseIndex: number) => void;
  onBoardActionTriggered?: (action: BoardAction) => void;
  onQuestionAsked?: (question: NonNullable<TeachingSegment['question']>) => void;
  onAnswerEvaluated?: (evaluation: StudentAnswerEvaluation) => void;
  onAudioPlaybackStateChanged?: (isPlaying: boolean) => void;
  onError?: (error: Error) => void;
}

export class TeachingEngineService {
  private appSettings: AppSettings;
  private userProfile: UserProfile | null;
  private voice: string = 'Jennifer';
  private currentSegment: TeachingSegment | null = null;
  private listeners: Set<TeachingEngineListener> = new Set();
  private isDestroyed = false;
  private activeAudioPlayer: any = null;
  private activeTimers: ReturnType<typeof setTimeout>[] = [];

  constructor(appSettings: AppSettings, userProfile: UserProfile | null = null, voice: string = 'Jennifer') {
    this.appSettings = appSettings;
    this.userProfile = userProfile;
    this.voice = voice || 'Jennifer';
  }

  public setVoice(voice: string) {
    this.voice = voice;
  }

  public getVoice(): string {
    return this.voice;
  }

  public updateSettings(newSettings: AppSettings, newProfile?: UserProfile | null) {
    this.appSettings = newSettings;
    if (newProfile !== undefined) this.userProfile = newProfile;
  }

  public subscribe(listener: TeachingEngineListener): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  public async loadSegment(params: {
    topic: string;
    courseName?: string;
    syllabusContext?: string;
    segmentNumber: number;
    studentName?: string;
    previousSegmentsSummary?: string;
    studentKnowledgeLevel?: string;
  }): Promise<TeachingSegment | null> {
    try {
      const ai = createAvelutAI(this.appSettings, this.userProfile);
      if (!ai) throw new Error('AI client could not be initialized');

      const resolvedStudentName = params.studentName || this.userProfile?.display_name || 'Student';

      const prompt = buildLessonSegmentPrompt({
        ...params,
        studentName: resolvedStudentName,
        isOpening: params.segmentNumber === 1,
      });

      const response = await ai.models.generateContent({
        model: this.appSettings.alibaba_model || 'qwen3.7-flash',
        contents: [
          { role: 'user', parts: [{ text: `${TEACHING_DIRECTOR_SYSTEM_PROMPT}\n\n${prompt}` }] }
        ],
        config: {
          responseMimeType: 'application/json',
          temperature: 0.35,
        }
      });

      const rawText = getResponseText(response);
      if (!rawText) throw new Error('Empty TeachingScript generated by AI');

      const segment = this.parseTeachingScriptJson(rawText, params.topic, params.segmentNumber);
      // Force clear between boards so diagrams/text never stick
      if (!segment.teaching.boardTransition || segment.teaching.boardTransition === 'none') {
        segment.teaching.boardTransition = 'clear_board';
      }
      this.currentSegment = segment;

      this.listeners.forEach((l) => l.onSegmentLoaded?.(segment));
      return segment;
    } catch (err: any) {
      console.error('[TeachingEngine] Error loading segment:', err);
      this.listeners.forEach((l) => l.onError?.(err instanceof Error ? err : new Error(String(err))));
      return null;
    }
  }

  public async playSegmentSpeech(segment: TeachingSegment): Promise<void> {
    if (this.isDestroyed || !segment.teaching.speech) return;

    this.stopCurrentPlayback();
    // Do NOT mark playing yet — wait until audio actually starts

    try {
      const speechText = segment.teaching.speech.trim();
      const actions = segment.teaching.actions || [];
      const triggeredActionIds = new Set<string>();
      let audioStarted = false;

      const fireAction = (act: BoardAction) => {
        if (triggeredActionIds.has(act.id)) return;
        triggeredActionIds.add(act.id);
        this.listeners.forEach((l) => l.onBoardActionTriggered?.(act));
      };

      this.activeAudioPlayer = unifiedVoiceRouter.playSpeech(speechText, {
        appSettings: this.appSettings,
        provider: 'grok',
        voice: this.voice,
        speed: 1.15,
        onStart: () => {
          if (this.isDestroyed) return;
          audioStarted = true;
          this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(true));
          // Start fallback action schedule only AFTER voice has begun
          this.scheduleSynchronizedActions(speechText, actions, triggeredActionIds);
        },
        onTimeUpdate: (currentTime) => {
          if (this.isDestroyed || !actions.length) return;
          if (!audioStarted) {
            audioStarted = true;
            this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(true));
            this.scheduleSynchronizedActions(speechText, actions, triggeredActionIds);
          }

          const words = speechText.split(/\s+/).length || 1;
          const estTotalSec = words / 2.8;

          actions.forEach((act) => {
            if (triggeredActionIds.has(act.id)) return;
            let targetTime = 0;
            if (act.sync?.phrase) {
              const phraseLower = act.sync.phrase.toLowerCase();
              const speechLower = speechText.toLowerCase();
              const charIdx = speechLower.indexOf(phraseLower);
              if (charIdx !== -1) {
                targetTime = (charIdx / Math.max(1, speechLower.length)) * estTotalSec;
              }
            }
            if (currentTime >= targetTime) {
              fireAction(act);
            }
          });
        },
        onEnd: () => {
          actions.forEach((act) => fireAction(act));
          this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(false));
          if (segment.question && segment.question.waitForAnswer) {
            this.listeners.forEach((l) => l.onQuestionAsked?.(segment.question!));
          }
        },
        onError: (err) => {
          console.warn('[TeachingEngine] Audio player error:', err);
          // Soft fallback: mark ready and stagger actions so board is not empty forever
          this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(true));
          this.scheduleSynchronizedActions(speechText, actions, triggeredActionIds);
          setTimeout(() => {
            this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(false));
          }, 4000);
        },
      });

      // Safety: if provider never fires onStart/onTimeUpdate within 2.5s, unlock board
      const safety = setTimeout(() => {
        if (!audioStarted && !this.isDestroyed) {
          audioStarted = true;
          this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(true));
          this.scheduleSynchronizedActions(speechText, actions, triggeredActionIds);
        }
      }, 2500);
      this.activeTimers.push(safety);
    } catch (err: any) {
      console.warn('[TeachingEngine] Speech playback fallback:', err);
      this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(true));
      segment.teaching.actions.forEach((act, idx) => {
        const timer = setTimeout(() => {
          this.listeners.forEach((l) => l.onBoardActionTriggered?.(act));
        }, 400 + idx * 700);
        this.activeTimers.push(timer);
      });
      setTimeout(() => {
        this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(false));
      }, 5000);
    }
  }

  public async evaluateStudentAnswer(params: {
    topic: string;
    studentAnswer: string;
  }): Promise<StudentAnswerEvaluation | null> {
    if (!this.currentSegment || !this.currentSegment.question) return null;

    try {
      const ai = createAvelutAI(this.appSettings, this.userProfile);
      if (!ai) throw new Error('AI client could not be initialized');

      const prompt = buildStudentAnswerEvaluationPrompt({
        topic: params.topic,
        segmentTitle: this.currentSegment.lesson.title,
        question: this.currentSegment.question.question,
        expectedConcepts: this.currentSegment.question.expectedConcepts,
        studentAnswer: params.studentAnswer,
      });

      const response = await ai.models.generateContent({
        model: this.appSettings.alibaba_model || 'qwen3.7-flash',
        contents: [
          { role: 'user', parts: [{ text: `${TEACHING_DIRECTOR_SYSTEM_PROMPT}\n\n${prompt}` }] }
        ],
        config: {
          responseMimeType: 'application/json',
          temperature: 0.3,
        }
      });

      const rawText = getResponseText(response);
      const cleaned = (rawText || '').replace(/```(?:json)?\s*/gi, '').replace(/\s*```$/gi, '').trim();
      const evaluation: StudentAnswerEvaluation = JSON.parse(cleaned);

      this.listeners.forEach((l) => l.onAnswerEvaluated?.(evaluation));

      if (evaluation.spokenFeedback) {
        unifiedVoiceRouter.playSpeech(evaluation.spokenFeedback, {
          appSettings: this.appSettings,
          provider: 'alibaba',
          voice: this.voice,
          speed: 1.05,
        });
      }

      if (evaluation.boardActions && evaluation.boardActions.length > 0) {
        evaluation.boardActions.forEach((act) => {
          this.listeners.forEach((l) => l.onBoardActionTriggered?.(act));
        });
      }

      return evaluation;
    } catch (err: any) {
      console.error('[TeachingEngine] Answer evaluation error:', err);
      const fallback: StudentAnswerEvaluation = {
        isCorrect: true,
        score: 'correct',
        spokenFeedback: "Good thinking! That's aligned with our core principle. Let's keep going.",
      };
      this.listeners.forEach((l) => l.onAnswerEvaluated?.(fallback));
      return fallback;
    }
  }

  public async askLecturerQuestion(params: {
    topic: string;
    studentQuestion: string;
  }): Promise<{ spokenAnswer: string; boardActions?: BoardAction[] }> {
    this.stopCurrentPlayback();

    try {
      const ai = createAvelutAI(this.appSettings, this.userProfile);
      if (!ai) throw new Error('AI client could not be initialized');

      const { buildStudentInterruptionPrompt } = await import('./teachingEnginePrompt');
      const prompt = buildStudentInterruptionPrompt({
        topic: params.topic,
        currentSegmentTitle: this.currentSegment?.lesson.title || params.topic,
        studentQuestion: params.studentQuestion,
      });

      const response = await ai.models.generateContent({
        model: this.appSettings.alibaba_model || 'qwen3.7-flash',
        contents: [
          { role: 'user', parts: [{ text: `${TEACHING_DIRECTOR_SYSTEM_PROMPT}\n\n${prompt}` }] }
        ],
        config: {
          responseMimeType: 'application/json',
          temperature: 0.3,
        }
      });

      const rawText = getResponseText(response);
      const cleaned = (rawText || '').replace(/```(?:json)?\s*/gi, '').replace(/\s*```$/gi, '').trim();
      const result = JSON.parse(cleaned);

      if (result.spokenAnswer) {
        unifiedVoiceRouter.playSpeech(result.spokenAnswer, {
          appSettings: this.appSettings,
          provider: 'alibaba',
          voice: this.voice,
          speed: 1.05,
        });
      }

      if (result.boardActions && Array.isArray(result.boardActions)) {
        result.boardActions.forEach((act: BoardAction) => {
          this.listeners.forEach((l) => l.onBoardActionTriggered?.(act));
        });
      }

      return result;
    } catch (err) {
      console.warn('[TeachingEngine] Interruption question error:', err);
      const fallbackAnswer = `Great question! When we look at ${params.topic}, this principle ensures all elements remain balanced and clear on our board.`;
      unifiedVoiceRouter.playSpeech(fallbackAnswer, {
        appSettings: this.appSettings,
        provider: 'alibaba',
        voice: this.voice,
      });
      return { spokenAnswer: fallbackAnswer };
    }
  }

  private scheduleSynchronizedActions(
    speech: string,
    actions: BoardAction[],
    triggeredIds: Set<string>
  ) {
    const words = speech.split(/\s+/);
    const totalWords = words.length || 1;
    const estTotalDurationMs = Math.max(2500, (totalWords / 2.8) * 1000);

    actions.forEach((action, index) => {
      let delayMs = 0;

      if (action.sync?.phrase) {
        const phraseLower = action.sync.phrase.toLowerCase();
        const speechLower = speech.toLowerCase();
        const charIndex = speechLower.indexOf(phraseLower);
        if (charIndex !== -1) {
          delayMs = Math.floor((charIndex / Math.max(1, speechLower.length)) * estTotalDurationMs);
        } else {
          delayMs = Math.floor(((index + 1) / Math.max(1, actions.length + 1)) * estTotalDurationMs * 0.75);
        }
      } else {
        delayMs = Math.floor(((index + 1) / Math.max(1, actions.length + 1)) * estTotalDurationMs * 0.75);
      }

      // Small lead so text appears as the phrase is spoken, not before audio exists
      const timer = setTimeout(() => {
        if (this.isDestroyed) return;
        if (triggeredIds.has(action.id)) return;
        triggeredIds.add(action.id);
        this.listeners.forEach((l) => l.onBoardActionTriggered?.(action));
      }, Math.max(120, delayMs));

      this.activeTimers.push(timer);
    });
  }

  private parseTeachingScriptJson(raw: string, topic: string, segmentNum: number): TeachingSegment {
    try {
      const cleaned = raw.replace(/```(?:json)?\s*/gi, '').replace(/\s*```$/gi, '').trim();
      const firstBrace = cleaned.indexOf('{');
      const lastBrace = cleaned.lastIndexOf('}');
      const jsonString = firstBrace !== -1 && lastBrace !== -1 ? cleaned.substring(firstBrace, lastBrace + 1) : cleaned;
      return JSON.parse(jsonString) as TeachingSegment;
    } catch (_) {
      return {
        lesson: {
          id: topic.toLowerCase().replace(/[^a-z0-9]/g, '-'),
          topic,
          segmentId: `seg_${segmentNum}`,
          title: 'Core Idea',
          segmentNumber: segmentNum,
          totalEstimatedSegments: 10,
        },
        teaching: {
          objective: `Build intuition for ${topic}`,
          speech: `Alright... let's look at ${topic} together. The core idea is simple once we put it on the board.`,
          boardTransition: 'clear_board',
          actions: [
            {
              id: `title_${segmentNum}`,
              type: 'write',
              persistence: 'persistent',
              content: topic,
              position: { x: 50, y: 12 },
              sync: { phrase: topic },
              metadata: { fontSize: 'xl', color: '#FFFFFF' },
            },
          ],
        },
        question: null,
        next: { type: 'continue' },
      };
    }
  }

  public stopCurrentPlayback() {
    this.activeTimers.forEach((t) => clearTimeout(t));
    this.activeTimers = [];
    if (this.activeAudioPlayer) {
      try {
        if (typeof this.activeAudioPlayer.stop === 'function') this.activeAudioPlayer.stop();
        else if (typeof this.activeAudioPlayer.pause === 'function') this.activeAudioPlayer.pause();
      } catch (_) {}
    }
    unifiedVoiceRouter.stopAudio();
  }

  public destroy() {
    this.isDestroyed = true;
    this.stopCurrentPlayback();
    unifiedVoiceRouter.stopAll();
    this.listeners.clear();
  }
}
