/**
 * Teaching Engine Service
 * Orchestrates live AI tutoring sessions:
 * - Directs Qwen3.7-Flash to generate TeachingScript segments
 * - Synchronizes spoken voice (Qwen3-TTS / UnifiedTTS) with whiteboard vector primitives
 * - Executes interactive question loops with conversational feedback and corrective board updates
 */

import { TeachingSegment, BoardAction, StudentAnswerEvaluation, TeachingSessionSummary } from '../types/teachingScript';
import { TEACHING_DIRECTOR_SYSTEM_PROMPT, buildLessonSegmentPrompt, buildStudentAnswerEvaluationPrompt } from './teachingEnginePrompt';
import { createAvelutAI, getResponseText } from '../utils/inference';
import { unifiedVoiceRouter } from './voice/UnifiedVoiceRouter';
import { AppSettings, UserProfile } from '../types';

export interface TeachingEngineListener {
  onSegmentLoaded?: (segment: TeachingSegment) => void;
  onSpokenWord?: (word: string, phraseIndex: number) => void;
  onBoardActionTriggered?: (action: BoardAction) => void;
  onQuestionAsked?: (question: NonNullable<TeachingSegment['question']>) => void;
  onAnswerEvaluated?: (evaluation: StudentAnswerEvaluation) => void;
  onAudioPlaybackStateChanged?: (isPlaying: boolean) => void;
  onError?: (error: Error) => void;
}

export class TeachingEngineService {
  private appSettings: AppSettings;
  private userProfile: UserProfile | null;
  private voice: string = 'Jennifer';
  private currentSegment: TeachingSegment | null = null;
  private listeners: Set<TeachingEngineListener> = new Set();
  private isDestroyed = false;
  private completedSegments: TeachingSegment[] = [];
  private activeAudioPlayer: any = null;
  private activeTimers: ReturnType<typeof setTimeout>[] = [];

  constructor(appSettings: AppSettings, userProfile: UserProfile | null = null, voice: string = 'Jennifer') {
    this.appSettings = appSettings;
    this.userProfile = userProfile;
    this.voice = voice || 'Jennifer';
  }

  public setVoice(voice: string) {
    this.voice = voice;
  }

  public getVoice(): string {
    return this.voice;
  }

  public updateSettings(newSettings: AppSettings, newProfile?: UserProfile | null) {
    this.appSettings = newSettings;
    if (newProfile !== undefined) this.userProfile = newProfile;
  }

  public subscribe(listener: TeachingEngineListener): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  /**
   * Generates and starts a teaching segment
   */
  public async loadSegment(params: {
    topic: string;
    courseName?: string;
    syllabusContext?: string;
    segmentNumber: number;
    previousSegmentsSummary?: string;
    studentKnowledgeLevel?: string;
  }): Promise<TeachingSegment | null> {
    try {
      const ai = createAvelutAI(this.appSettings, this.userProfile);
      if (!ai) throw new Error('AI client could not be initialized');

      const prompt = buildLessonSegmentPrompt({
        ...params,
        isOpening: params.segmentNumber === 1,
      });

      const response = await ai.models.generateContent({
        model: this.appSettings.alibaba_model || 'qwen3.7-flash',
        contents: [
          { role: 'user', parts: [{ text: `${TEACHING_DIRECTOR_SYSTEM_PROMPT}\n\n${prompt}` }] }
        ],
        config: {
          responseMimeType: 'application/json',
          temperature: 0.35,
        }
      });

      const rawText = getResponseText(response);
      if (!rawText) throw new Error('Empty TeachingScript generated by AI');

      const segment = this.parseTeachingScriptJson(rawText, params.topic, params.segmentNumber);
      this.currentSegment = segment;

      this.listeners.forEach((l) => l.onSegmentLoaded?.(segment));
      return segment;
    } catch (err: any) {
      console.error('[TeachingEngine] Error loading segment:', err);
      this.listeners.forEach((l) => l.onError?.(err instanceof Error ? err : new Error(String(err))));
      return null;
    }
  }

  /**
   * Synthesizes voice for the segment and schedules synchronized board actions
   */
  public async playSegmentSpeech(segment: TeachingSegment): Promise<void> {
    if (this.isDestroyed || !segment.teaching.speech) return;

    this.stopCurrentPlayback();
    this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(true));

    try {
      const speechText = segment.teaching.speech.trim();
      const actions = segment.teaching.actions || [];

      // Start audio synthesis via UnifiedVoiceRouter with fast 1.15x lecturer pace
      this.activeAudioPlayer = unifiedVoiceRouter.playSpeech(speechText, {
        appSettings: this.appSettings,
        provider: 'grok',
        voice: this.voice,
        speed: 1.15,
        onEnd: () => {
          this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(false));
          if (segment.question && segment.question.waitForAnswer) {
            this.listeners.forEach((l) => l.onQuestionAsked?.(segment.question!));
          }
        },
        onError: (err) => {
          console.warn('[TeachingEngine] Audio player error:', err);
          this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(false));
        },
      });

      // Schedule fast, snappy synchronized board actions
      this.scheduleSynchronizedActions(speechText, actions);
    } catch (err: any) {
      console.warn('[TeachingEngine] Speech playback fallback:', err);
      // Fallback: immediately trigger actions
      segment.teaching.actions.forEach((act, idx) => {
        const timer = setTimeout(() => {
          this.listeners.forEach((l) => l.onBoardActionTriggered?.(act));
        }, idx * 600);
        this.activeTimers.push(timer);
      });
      this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(false));
    }
  }

  /**
   * Evaluates student's answer to a teaching question
   */
  public async evaluateStudentAnswer(params: {
    topic: string;
    studentAnswer: string;
  }): Promise<StudentAnswerEvaluation | null> {
    if (!this.currentSegment || !this.currentSegment.question) return null;

    try {
      const ai = createAvelutAI(this.appSettings, this.userProfile);
      if (!ai) throw new Error('AI client could not be initialized');

      const prompt = buildStudentAnswerEvaluationPrompt({
        topic: params.topic,
        segmentTitle: this.currentSegment.lesson.title,
        question: this.currentSegment.question.question,
        expectedConcepts: this.currentSegment.question.expectedConcepts,
        studentAnswer: params.studentAnswer,
      });

      const response = await ai.models.generateContent({
        model: this.appSettings.alibaba_model || 'qwen3.7-flash',
        contents: [
          { role: 'user', parts: [{ text: `${TEACHING_DIRECTOR_SYSTEM_PROMPT}\n\n${prompt}` }] }
        ],
        config: {
          responseMimeType: 'application/json',
          temperature: 0.3,
        }
      });

      const rawText = getResponseText(response);
      const cleaned = (rawText || '').replace(/```(?:json)?\s*/gi, '').replace(/\s*```$/gi, '').trim();
      const evaluation: StudentAnswerEvaluation = JSON.parse(cleaned);

      this.listeners.forEach((l) => l.onAnswerEvaluated?.(evaluation));

      // Speak feedback and trigger corrective board actions if present
      if (evaluation.spokenFeedback) {
        unifiedVoiceRouter.playSpeech(evaluation.spokenFeedback, {
          appSettings: this.appSettings,
          provider: 'alibaba',
          voice: this.voice,
          speed: 1.05,
        });
      }

      if (evaluation.boardActions && evaluation.boardActions.length > 0) {
        evaluation.boardActions.forEach((act) => {
          this.listeners.forEach((l) => l.onBoardActionTriggered?.(act));
        });
      }

      return evaluation;
    } catch (err: any) {
      console.error('[TeachingEngine] Answer evaluation error:', err);
      // Fallback evaluation
      const fallback: StudentAnswerEvaluation = {
        isCorrect: true,
        score: 'correct',
        spokenFeedback: "Good thinking! That's aligned with our core principle. Let's keep going.",
      };
      this.listeners.forEach((l) => l.onAnswerEvaluated?.(fallback));
      return fallback;
    }
  }

  /**
   * Handles real-time student interruption questions ("Ask the Lecturer")
   */
  public async askLecturerQuestion(params: {
    topic: string;
    studentQuestion: string;
  }): Promise<{ spokenAnswer: string; boardActions?: BoardAction[] }> {
    this.stopCurrentPlayback();

    try {
      const ai = createAvelutAI(this.appSettings, this.userProfile);
      if (!ai) throw new Error('AI client could not be initialized');

      const { buildStudentInterruptionPrompt } = await import('./teachingEnginePrompt');
      const prompt = buildStudentInterruptionPrompt({
        topic: params.topic,
        currentSegmentTitle: this.currentSegment?.lesson.title || params.topic,
        studentQuestion: params.studentQuestion,
      });

      const response = await ai.models.generateContent({
        model: this.appSettings.alibaba_model || 'qwen3.7-flash',
        contents: [
          { role: 'user', parts: [{ text: `${TEACHING_DIRECTOR_SYSTEM_PROMPT}\n\n${prompt}` }] }
        ],
        config: {
          responseMimeType: 'application/json',
          temperature: 0.3,
        }
      });

      const rawText = getResponseText(response);
      const cleaned = (rawText || '').replace(/```(?:json)?\s*/gi, '').replace(/\s*```$/gi, '').trim();
      const result = JSON.parse(cleaned);

      if (result.spokenAnswer) {
        unifiedVoiceRouter.playSpeech(result.spokenAnswer, {
          appSettings: this.appSettings,
          provider: 'alibaba',
          voice: this.voice,
          speed: 1.05,
        });
      }

      if (result.boardActions && Array.isArray(result.boardActions)) {
        result.boardActions.forEach((act: BoardAction) => {
          this.listeners.forEach((l) => l.onBoardActionTriggered?.(act));
        });
      }

      return result;
    } catch (err) {
      console.warn('[TeachingEngine] Interruption question error:', err);
      const fallbackAnswer = `Great question! When we look at ${params.topic}, this principle ensures all elements remain balanced and clear on our board.`;
      unifiedVoiceRouter.playSpeech(fallbackAnswer, {
        appSettings: this.appSettings,
        provider: 'alibaba',
        voice: this.voice,
      });
      return { spokenAnswer: fallbackAnswer };
    }
  }

  private scheduleSynchronizedActions(speech: string, actions: BoardAction[]) {
    const words = speech.split(/\s+/);
    const totalWords = words.length || 1;
    // Faster action pacing (2.8 words/sec)
    const estTotalDurationMs = Math.max(2000, (totalWords / 2.8) * 1000);

    actions.forEach((action, index) => {
      let delayMs = 0;

      if (action.sync?.phrase) {
        const phraseLower = action.sync.phrase.toLowerCase();
        const speechLower = speech.toLowerCase();
        const charIndex = speechLower.indexOf(phraseLower);
        if (charIndex !== -1) {
          const ratio = charIndex / speechLower.length;
          delayMs = Math.floor(ratio * estTotalDurationMs);
        } else {
          delayMs = Math.floor((index / Math.max(1, actions.length)) * estTotalDurationMs * 0.8);
        }
      } else {
        delayMs = Math.floor((index / Math.max(1, actions.length)) * estTotalDurationMs * 0.8);
      }

      // Fast, snappy action triggers with lead delay of 80ms
      const timer = setTimeout(() => {
        if (!this.isDestroyed) {
          this.listeners.forEach((l) => l.onBoardActionTriggered?.(action));
        }
      }, Math.max(80, delayMs));

      this.activeTimers.push(timer);
    });
  }

  private parseTeachingScriptJson(raw: string, topic: string, segmentNum: number): TeachingSegment {
    try {
      const cleaned = raw.replace(/```(?:json)?\s*/gi, '').replace(/\s*```$/gi, '').trim();
      const firstBrace = cleaned.indexOf('{');
      const lastBrace = cleaned.lastIndexOf('}');
      const jsonString = firstBrace !== -1 && lastBrace !== -1 ? cleaned.substring(firstBrace, lastBrace + 1) : cleaned;
      return JSON.parse(jsonString) as TeachingSegment;
    } catch (_) {
      // Clean fallback segment
      return {
        lesson: {
          id: topic.toLowerCase().replace(/[^a-z0-9]/g, '-'),
          topic,
          segmentId: `seg_${segmentNum}`,
          title: 'Foundations & Intuition',
          segmentNumber: segmentNum,
          totalEstimatedSegments: 5,
        },
        teaching: {
          objective: `Build foundational intuition for ${topic}`,
          speech: `Let's explore ${topic} step by step on our whiteboard so every core principle becomes crystal clear.`,
          actions: [
            {
              id: `act_${segmentNum}_1`,
              type: 'write',
              content: topic,
              sync: { phrase: topic },
              metadata: { x: 50, y: 30 }
            }
          ]
        },
        question: {
          id: `q_${segmentNum}`,
          type: 'understanding',
          question: `What is the primary concept behind ${topic}?`,
          waitForAnswer: true,
        },
        next: {
          type: 'wait_for_answer'
        }
      };
    }
  }

  public stopCurrentPlayback() {
    this.activeTimers.forEach((t) => clearTimeout(t));
    this.activeTimers = [];
    if (this.activeAudioPlayer) {
      try {
        if (typeof this.activeAudioPlayer.stop === 'function') {
          this.activeAudioPlayer.stop();
        } else if (typeof this.activeAudioPlayer.pause === 'function') {
          this.activeAudioPlayer.pause();
        }
      } catch (_) {}
    }
    unifiedVoiceRouter.stopAudio();
  }

  public destroy() {
    this.isDestroyed = true;
    this.stopCurrentPlayback();
    unifiedVoiceRouter.stopAll();
    this.listeners.clear();
  }
}
