/**
 * Teaching Engine Service
 * - Word-index timeline with minimum gap between successive write reveals (~10s)
 * - Pause / resume for interruptions
 */

import { TeachingSegment, BoardAction, StudentAnswerEvaluation } from '../types/teachingScript';
import { TEACHING_DIRECTOR_SYSTEM_PROMPT, buildLessonSegmentPrompt, buildStudentAnswerEvaluationPrompt } from './teachingEnginePrompt';
import { createAvelutAI, getResponseText } from '../utils/inference';
import { unifiedVoiceRouter } from './voice/UnifiedVoiceRouter';
import { AppSettings, UserProfile } from '../types';

export interface TeachingEngineListener {
  onSegmentLoaded?: (segment: TeachingSegment) => void;
  onSpokenWord?: (word: string, phraseIndex: number) => void;
  onBoardActionTriggered?: (action: BoardAction) => void;
  onQuestionAsked?: (question: NonNullable<TeachingSegment['question']>) => void;
  onAnswerEvaluated?: (evaluation: StudentAnswerEvaluation) => void;
  onAudioPlaybackStateChanged?: (isPlaying: boolean) => void;
  onError?: (error: Error) => void;
}

function wordsPerSecond(speed: number): number {
  return Math.max(2.2, 2.55 * speed);
}

function phraseWordOffset(speech: string, phrase: string | undefined): number {
  if (!phrase) return 0;
  const speechLower = speech.toLowerCase();
  const phraseLower = phrase.toLowerCase().trim();
  const charIdx = speechLower.indexOf(phraseLower);
  if (charIdx === -1) return -1;
  return speechLower.slice(0, charIdx).trim().split(/\s+/).filter(Boolean).length;
}

/** Minimum ms between successive board writes so key points are not stacked in 1s */
const MIN_WRITE_GAP_MS = 9500;
const MIN_ANY_GAP_MS = 2800;

export class TeachingEngineService {
  private appSettings: AppSettings;
  private userProfile: UserProfile | null;
  private voice: string = 'Altair';
  private currentSegment: TeachingSegment | null = null;
  private listeners: Set<TeachingEngineListener> = new Set();
  private isDestroyed = false;
  private activeAudioPlayer: any = null;
  private activeTimers: ReturnType<typeof setTimeout>[] = [];
  private isPaused = false;
  private pausedSegment: TeachingSegment | null = null;

  constructor(appSettings: AppSettings, userProfile: UserProfile | null = null, voice: string = 'Altair') {
    this.appSettings = appSettings;
    this.userProfile = userProfile;
    this.voice = voice || 'Altair';
  }

  public setVoice(voice: string) {
    this.voice = voice;
  }

  public getVoice(): string {
    return this.voice;
  }

  public updateSettings(newSettings: AppSettings, newProfile?: UserProfile | null) {
    this.appSettings = newSettings;
    if (newProfile !== undefined) this.userProfile = newProfile;
  }

  public subscribe(listener: TeachingEngineListener): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  public getCurrentSegment(): TeachingSegment | null {
    return this.currentSegment;
  }

  public pauseLesson() {
    this.isPaused = true;
    this.pausedSegment = this.currentSegment;
    this.activeTimers.forEach((t) => clearTimeout(t));
    this.activeTimers = [];
    if (this.activeAudioPlayer) {
      try {
        if (typeof this.activeAudioPlayer.pause === 'function') this.activeAudioPlayer.pause();
        else if (typeof this.activeAudioPlayer.stop === 'function') this.activeAudioPlayer.stop();
      } catch (_) {}
    }
    unifiedVoiceRouter.stopAudio();
    this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(false));
  }

  public resumeLesson() {
    this.isPaused = false;
    const seg = this.pausedSegment || this.currentSegment;
    this.pausedSegment = null;
    if (seg) this.playSegmentSpeech(seg);
  }

  public async loadSegment(params: {
    topic: string;
    courseName?: string;
    syllabusContext?: string;
    segmentNumber: number;
    studentName?: string;
    previousSegmentsSummary?: string;
    studentKnowledgeLevel?: string;
  }): Promise<TeachingSegment | null> {
    try {
      const ai = createAvelutAI(this.appSettings, this.userProfile);
      if (!ai) throw new Error('AI client could not be initialized');

      const resolvedStudentName =
        params.studentName || this.userProfile?.display_name || 'Student';

      const prompt = buildLessonSegmentPrompt({
        ...params,
        studentName: resolvedStudentName,
        isOpening: params.segmentNumber === 1,
      });

      const response = await ai.models.generateContent({
        model: this.appSettings.alibaba_model || 'qwen3.7-flash',
        contents: [{ role: 'user', parts: [{ text: `${TEACHING_DIRECTOR_SYSTEM_PROMPT}\n\n${prompt}` }] }],
        config: {
          responseMimeType: 'application/json',
          temperature: 0.35,
        },
      });

      const rawText = getResponseText(response);
      if (!rawText) throw new Error('Empty TeachingScript generated by AI');

      const segment = this.parseTeachingScriptJson(rawText, params.topic, params.segmentNumber);
      if (!segment.teaching.boardTransition || segment.teaching.boardTransition === 'none') {
        segment.teaching.boardTransition = 'clear_board';
      }
      this.currentSegment = segment;
      this.listeners.forEach((l) => l.onSegmentLoaded?.(segment));
      return segment;
    } catch (err: any) {
      console.error('[TeachingEngine] Error loading segment:', err);
      this.listeners.forEach((l) => l.onError?.(err instanceof Error ? err : new Error(String(err))));
      return null;
    }
  }

  public async playSegmentSpeech(segment: TeachingSegment): Promise<void> {
    if (this.isDestroyed || !segment.teaching.speech) return;

    this.stopCurrentPlayback();
    this.isPaused = false;

    try {
      const speechText = segment.teaching.speech.trim();
      const actions = segment.teaching.actions || [];
      const triggeredActionIds = new Set<string>();
      let audioStarted = false;
      const speed = 1.12;
      const wps = wordsPerSecond(speed);

      const fireAction = (act: BoardAction) => {
        if (triggeredActionIds.has(act.id)) return;
        triggeredActionIds.add(act.id);
        this.listeners.forEach((l) => l.onBoardActionTriggered?.(act));
      };

      this.activeAudioPlayer = unifiedVoiceRouter.playSpeech(speechText, {
        appSettings: this.appSettings,
        voice: this.voice,
        speed,
        onStart: () => {
          if (this.isDestroyed || this.isPaused) return;
          audioStarted = true;
          this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(true));
          this.scheduleWordTimeline(speechText, actions, triggeredActionIds, wps);
        },
        onTimeUpdate: (currentTime) => {
          if (this.isDestroyed || this.isPaused || !actions.length) return;
          if (!audioStarted) {
            audioStarted = true;
            this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(true));
            this.scheduleWordTimeline(speechText, actions, triggeredActionIds, wps);
          }

          // Prefer timer schedule; onTimeUpdate only as backup with same gaps enforced in schedule
          void currentTime;
        },
        onEnd: () => {
          if (this.isPaused) return;
          actions.forEach((act) => fireAction(act));
          this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(false));
          if (segment.question && segment.question.waitForAnswer) {
            this.listeners.forEach((l) => l.onQuestionAsked?.(segment.question!));
          }
        },
        onError: (err) => {
          console.warn('[TeachingEngine] Audio player error:', err);
          this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(true));
          this.scheduleWordTimeline(speechText, actions, triggeredActionIds, wps);
          setTimeout(() => {
            this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(false));
          }, 4000);
        },
      });

      const safety = setTimeout(() => {
        if (!audioStarted && !this.isDestroyed && !this.isPaused) {
          audioStarted = true;
          this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(true));
          this.scheduleWordTimeline(speechText, actions, triggeredActionIds, wps);
        }
      }, 1800);
      this.activeTimers.push(safety);
    } catch (err: any) {
      console.warn('[TeachingEngine] Speech playback fallback:', err);
      this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(true));
      segment.teaching.actions.forEach((act, idx) => {
        const timer = setTimeout(() => {
          this.listeners.forEach((l) => l.onBoardActionTriggered?.(act));
        }, 800 + idx * MIN_WRITE_GAP_MS);
        this.activeTimers.push(timer);
      });
      setTimeout(() => {
        this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(false));
      }, 800 + segment.teaching.actions.length * MIN_WRITE_GAP_MS);
    }
  }

  /**
   * Schedule actions by phrase position in speech, then ENFORCE minimum gaps
   * so consecutive write/key-points cannot fire 1 second apart.
   */
  private scheduleWordTimeline(
    speech: string,
    actions: BoardAction[],
    triggeredIds: Set<string>,
    wps: number
  ) {
    const words = speech.split(/\s+/).filter(Boolean);
    const totalWords = words.length || 1;
    const estTotalMs = Math.max(45000, (totalWords / wps) * 1000);

    // Compute ideal times from phrase offsets
    const planned: { action: BoardAction; at: number }[] = actions.map((action, index) => {
      let delayMs = 0;
      const offset = phraseWordOffset(speech, action.sync?.phrase);
      if (offset >= 0) {
        delayMs = Math.floor((offset / wps) * 1000);
      } else {
        delayMs = Math.floor(((index + 1) / Math.max(1, actions.length + 1)) * estTotalMs * 0.85);
      }
      return { action, at: Math.max(400, delayMs) };
    });

    // Sort by planned time, then push writes apart by MIN_WRITE_GAP_MS
    planned.sort((a, b) => a.at - b.at);
    let lastWriteAt = -MIN_WRITE_GAP_MS;
    let lastAnyAt = -MIN_ANY_GAP_MS;

    planned.forEach((item) => {
      const isWrite = item.action.type === 'write' || item.action.type === 'label';
      let t = item.at;
      if (isWrite) {
        t = Math.max(t, lastWriteAt + MIN_WRITE_GAP_MS);
        lastWriteAt = t;
      } else {
        t = Math.max(t, lastAnyAt + MIN_ANY_GAP_MS);
      }
      lastAnyAt = t;
      item.at = t;
    });

    planned.forEach(({ action, at }) => {
      const timer = setTimeout(() => {
        if (this.isDestroyed || this.isPaused) return;
        if (triggeredIds.has(action.id)) return;
        triggeredIds.add(action.id);
        this.listeners.forEach((l) => l.onBoardActionTriggered?.(action));
      }, at);
      this.activeTimers.push(timer);
    });
  }

  public async evaluateStudentAnswer(params: {
    topic: string;
    studentAnswer: string;
  }): Promise<StudentAnswerEvaluation | null> {
    if (!this.currentSegment || !this.currentSegment.question) return null;

    try {
      const ai = createAvelutAI(this.appSettings, this.userProfile);
      if (!ai) throw new Error('AI client could not be initialized');

      const prompt = buildStudentAnswerEvaluationPrompt({
        topic: params.topic,
        segmentTitle: this.currentSegment.lesson.title,
        question: this.currentSegment.question.question,
        expectedConcepts: this.currentSegment.question.expectedConcepts,
        studentAnswer: params.studentAnswer,
      });

      const response = await ai.models.generateContent({
        model: this.appSettings.alibaba_model || 'qwen3.7-flash',
        contents: [{ role: 'user', parts: [{ text: `${TEACHING_DIRECTOR_SYSTEM_PROMPT}\n\n${prompt}` }] }],
        config: { responseMimeType: 'application/json', temperature: 0.3 },
      });

      const rawText = getResponseText(response);
      const cleaned = (rawText || '').replace(/```(?:json)?\s*/gi, '').replace(/\s*```$/gi, '').trim();
      const evaluation: StudentAnswerEvaluation = JSON.parse(cleaned);
      this.listeners.forEach((l) => l.onAnswerEvaluated?.(evaluation));

      if (evaluation.spokenFeedback) {
        unifiedVoiceRouter.playSpeech(evaluation.spokenFeedback, {
          appSettings: this.appSettings,
          provider: 'alibaba',
          voice: this.voice,
          speed: 1.05,
        });
      }

      if (evaluation.boardActions?.length) {
        evaluation.boardActions.forEach((act) => {
          this.listeners.forEach((l) => l.onBoardActionTriggered?.(act));
        });
      }
      return evaluation;
    } catch (err: any) {
      console.error('[TeachingEngine] Answer evaluation error:', err);
      const fallback: StudentAnswerEvaluation = {
        isCorrect: true,
        score: 'correct',
        spokenFeedback: "Good thinking! Let's keep going.",
      };
      this.listeners.forEach((l) => l.onAnswerEvaluated?.(fallback));
      return fallback;
    }
  }

  public async askLecturerQuestion(params: {
    topic: string;
    studentQuestion: string;
  }): Promise<{ spokenAnswer: string; boardActions?: BoardAction[] }> {
    this.stopCurrentPlayback();

    try {
      const ai = createAvelutAI(this.appSettings, this.userProfile);
      if (!ai) throw new Error('AI client could not be initialized');

      const { buildStudentInterruptionPrompt } = await import('./teachingEnginePrompt');
      const prompt = buildStudentInterruptionPrompt({
        topic: params.topic,
        currentSegmentTitle: this.currentSegment?.lesson.title || params.topic,
        studentQuestion: params.studentQuestion,
      });

      const response = await ai.models.generateContent({
        model: this.appSettings.alibaba_model || 'qwen3.7-flash',
        contents: [{ role: 'user', parts: [{ text: `${TEACHING_DIRECTOR_SYSTEM_PROMPT}\n\n${prompt}` }] }],
        config: { responseMimeType: 'application/json', temperature: 0.3 },
      });

      const rawText = getResponseText(response);
      const cleaned = (rawText || '').replace(/```(?:json)?\s*/gi, '').replace(/\s*```$/gi, '').trim();
      const result = JSON.parse(cleaned);

      if (result.spokenAnswer) {
        const actions: BoardAction[] = Array.isArray(result.boardActions) ? result.boardActions : [];
        const triggered = new Set<string>();
        const wps = wordsPerSecond(1.05);

        this.activeAudioPlayer = unifiedVoiceRouter.playSpeech(result.spokenAnswer, {
          appSettings: this.appSettings,
          provider: 'alibaba',
          voice: this.voice,
          speed: 1.05,
          onStart: () => {
            this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(true));
            if (actions.length) this.scheduleWordTimeline(result.spokenAnswer, actions, triggered, wps);
          },
          onEnd: () => {
            actions.forEach((a) => {
              if (!triggered.has(a.id)) {
                triggered.add(a.id);
                this.listeners.forEach((l) => l.onBoardActionTriggered?.(a));
              }
            });
            this.listeners.forEach((l) => l.onAudioPlaybackStateChanged?.(false));
          },
        });
      }

      return result;
    } catch (err) {
      console.warn('[TeachingEngine] Interruption question error:', err);
      const fallbackAnswer = `Great question about ${params.topic}. Let me keep that clear for you on the board.`;
      unifiedVoiceRouter.playSpeech(fallbackAnswer, {
        appSettings: this.appSettings,
        provider: 'alibaba',
        voice: this.voice,
      });
      return { spokenAnswer: fallbackAnswer };
    }
  }

  private parseTeachingScriptJson(raw: string, topic: string, segmentNum: number): TeachingSegment {
    try {
      const cleaned = raw.replace(/```(?:json)?\s*/gi, '').replace(/\s*```$/gi, '').trim();
      const firstBrace = cleaned.indexOf('{');
      const lastBrace = cleaned.lastIndexOf('}');
      const jsonString =
        firstBrace !== -1 && lastBrace !== -1 ? cleaned.substring(firstBrace, lastBrace + 1) : cleaned;
      return JSON.parse(jsonString) as TeachingSegment;
    } catch (_) {
      return {
        lesson: {
          id: topic.toLowerCase().replace(/[^a-z0-9]/g, '-'),
          topic,
          segmentId: `seg_${segmentNum}`,
          title: 'Core Idea',
          segmentNumber: segmentNum,
          totalEstimatedSegments: 10,
        },
        teaching: {
          objective: `Build intuition for ${topic}`,
          speech: `Alright... let's look at ${topic} together. The core idea is simple once we put it on the board.`,
          boardTransition: 'clear_board',
          actions: [
            {
              id: `title_${segmentNum}`,
              type: 'write',
              persistence: 'persistent',
              content: topic,
              position: { x: 50, y: 10 },
              sync: { phrase: topic },
              metadata: { fontSize: 'xl', color: '#FFFFFF' },
            },
          ],
        },
        question: null,
        next: { type: 'continue' },
      };
    }
  }

  public stopCurrentPlayback() {
    this.activeTimers.forEach((t) => clearTimeout(t));
    this.activeTimers = [];
    if (this.activeAudioPlayer) {
      try {
        if (typeof this.activeAudioPlayer.stop === 'function') this.activeAudioPlayer.stop();
        else if (typeof this.activeAudioPlayer.pause === 'function') this.activeAudioPlayer.pause();
      } catch (_) {}
    }
    unifiedVoiceRouter.stopAudio();
  }

  public destroy() {
    this.isDestroyed = true;
    this.stopCurrentPlayback();
    unifiedVoiceRouter.stopAll();
    this.listeners.clear();
  }
}
