import type { AppSettings } from '../types';

export const APP_SETTINGS_PATH = 'app_settings/global';

export const DEFAULT_USAGE_SETTINGS = {
  tiers: {
    free: {
      tier_id: 'free',
      display_name: 'Forever Free',
      description: 'Fundamental study tools with standard constraints. Good for **upto 1 hour of studytime**.',
      price_ngn: 0,
      credit_allocation: 30,
      max_saved_courses: 2,
      has_verification_badge: false,
      badge_color: 'none',
    },
    basic: {
      tier_id: 'basic',
      display_name: 'Basic Plan',
      description: 'Unlock advanced guides and higher limits. Great for **upto 5 hours of studytime**.',
      price_ngn: 1000,
      credit_allocation: 500,
      max_saved_courses: 5,
      has_verification_badge: true,
      badge_color: 'blue',
    },
    premium: {
      tier_id: 'premium',
      display_name: 'Premium Pro',
      description: 'Ultimate academic assistance. Ideal for **unlimited studytime**.',
      price_ngn: 3000,
      credit_allocation: 2000,
      max_saved_courses: -1,
      has_verification_badge: true,
      badge_color: 'purple',
    },
  },
  feature_costs: {
    visual_solve: 4,
    chat_interaction: 1,
    flashcard_generation: 3,
    ai_quiz_generation: 2,
    study_guide_lesson: 1,
    study_guide_extraction: 10,
  },
  feature_models: {
    visual_solve: 'gemini-3.1-pro',
    chat_interaction: 'gemini-3.1-flash-lite',
    flashcard_generation: 'gemini-3.1-flash-lite',
    ai_quiz_generation: 'gemini-3.1-flash-lite',
    study_guide_lesson: 'gemini-3.1-flash-lite',
    study_guide_extraction: 'gemini-3.1-flash-lite',
    title_generation: 'gemini-3.1-flash-lite',
  },
  additional_prices: {
    visual_messages_price: 200,
    visual_messages_count: 10,
    studyguide_course_price: 300,
    studyguide_request_price: 50,
  },
};

export const DEFAULT_APP_SETTINGS: AppSettings = {
  primary_gemini_model: 'gemini-3.1-flash-lite',
  gemini_api_key: '',
  upload_center_uploads_enabled: true,
  coming_soon_enabled: false,
  show_playstore_modal: true,
  playstore_modal_collect_emails: true,
  paystack_public_key: '',
  paystack_secret_key: '',
  custom_user_limit_rpm: 10,
  custom_user_limit_tpm: 250000,
  usage_settings: DEFAULT_USAGE_SETTINGS as any, // Temporary cast until types propagate fully
  youtube_api_key: '',
  google_client_id: '',
  google_api_key: '',
  pinecone_api_key: '',
  pinecone_index_name: '',
  revenuecat_api_key_android: '',
};

export const normalizeAppSettings = (raw: Partial<AppSettings> | null | undefined): AppSettings => ({
  primary_gemini_model: (raw?.primary_gemini_model || DEFAULT_APP_SETTINGS.primary_gemini_model).toString().trim() || DEFAULT_APP_SETTINGS.primary_gemini_model,
  gemini_api_key: (raw?.gemini_api_key || DEFAULT_APP_SETTINGS.gemini_api_key).toString().trim(),
  youtube_api_key: (raw?.youtube_api_key || DEFAULT_APP_SETTINGS.youtube_api_key || '').toString().trim(),
  google_client_id: (raw?.google_client_id || DEFAULT_APP_SETTINGS.google_client_id || '').toString().trim(),
  google_api_key: (raw?.google_api_key || DEFAULT_APP_SETTINGS.google_api_key || '').toString().trim(),
  pinecone_api_key: (raw?.pinecone_api_key || DEFAULT_APP_SETTINGS.pinecone_api_key || '').toString().trim(),
  pinecone_index_name: (raw?.pinecone_index_name || DEFAULT_APP_SETTINGS.pinecone_index_name || '').toString().trim(),
  revenuecat_api_key_android: (raw?.revenuecat_api_key_android || DEFAULT_APP_SETTINGS.revenuecat_api_key_android || '').toString().trim(),
  upload_center_uploads_enabled: raw?.upload_center_uploads_enabled ?? DEFAULT_APP_SETTINGS.upload_center_uploads_enabled,
  coming_soon_enabled: raw?.coming_soon_enabled ?? DEFAULT_APP_SETTINGS.coming_soon_enabled,
  show_playstore_modal: raw?.show_playstore_modal ?? DEFAULT_APP_SETTINGS.show_playstore_modal,
  playstore_modal_collect_emails: raw?.playstore_modal_collect_emails ?? DEFAULT_APP_SETTINGS.playstore_modal_collect_emails,
  paystack_public_key: (raw?.paystack_public_key || DEFAULT_APP_SETTINGS.paystack_public_key).toString().trim(),
  paystack_secret_key: (raw?.paystack_secret_key || DEFAULT_APP_SETTINGS.paystack_secret_key).toString().trim(),
  custom_user_limit_rpm: typeof raw?.custom_user_limit_rpm === 'number' ? raw.custom_user_limit_rpm : DEFAULT_APP_SETTINGS.custom_user_limit_rpm,
  custom_user_limit_tpm: typeof raw?.custom_user_limit_tpm === 'number' ? raw.custom_user_limit_tpm : DEFAULT_APP_SETTINGS.custom_user_limit_tpm,
  usage_settings: raw?.usage_settings ? {
    feature_costs: {
      visual_solve: typeof raw.usage_settings.feature_costs?.visual_solve === 'number' ? raw.usage_settings.feature_costs.visual_solve : DEFAULT_USAGE_SETTINGS.feature_costs.visual_solve,
      chat_interaction: typeof raw.usage_settings.feature_costs?.chat_interaction === 'number' ? raw.usage_settings.feature_costs.chat_interaction : DEFAULT_USAGE_SETTINGS.feature_costs.chat_interaction,
      flashcard_generation: typeof raw.usage_settings.feature_costs?.flashcard_generation === 'number' ? raw.usage_settings.feature_costs.flashcard_generation : DEFAULT_USAGE_SETTINGS.feature_costs.flashcard_generation,
      ai_quiz_generation: typeof raw.usage_settings.feature_costs?.ai_quiz_generation === 'number' ? raw.usage_settings.feature_costs.ai_quiz_generation : DEFAULT_USAGE_SETTINGS.feature_costs.ai_quiz_generation,
      study_guide_lesson: typeof raw.usage_settings.feature_costs?.study_guide_lesson === 'number' ? raw.usage_settings.feature_costs.study_guide_lesson : DEFAULT_USAGE_SETTINGS.feature_costs.study_guide_lesson,
      study_guide_extraction: typeof raw.usage_settings.feature_costs?.study_guide_extraction === 'number' ? raw.usage_settings.feature_costs.study_guide_extraction : DEFAULT_USAGE_SETTINGS.feature_costs.study_guide_extraction,
    },
    feature_models: {
      visual_solve: raw.usage_settings.feature_models?.visual_solve || DEFAULT_USAGE_SETTINGS.feature_models.visual_solve,
      chat_interaction: raw.usage_settings.feature_models?.chat_interaction || DEFAULT_USAGE_SETTINGS.feature_models.chat_interaction,
      flashcard_generation: raw.usage_settings.feature_models?.flashcard_generation || DEFAULT_USAGE_SETTINGS.feature_models.flashcard_generation,
      ai_quiz_generation: raw.usage_settings.feature_models?.ai_quiz_generation || DEFAULT_USAGE_SETTINGS.feature_models.ai_quiz_generation,
      study_guide_lesson: raw.usage_settings.feature_models?.study_guide_lesson || DEFAULT_USAGE_SETTINGS.feature_models.study_guide_lesson,
      study_guide_extraction: raw.usage_settings.feature_models?.study_guide_extraction || DEFAULT_USAGE_SETTINGS.feature_models.study_guide_extraction,
      title_generation: raw.usage_settings.feature_models?.title_generation || DEFAULT_USAGE_SETTINGS.feature_models.title_generation,
    },
    tiers: {
      free: {
        tier_id: raw.usage_settings.tiers?.free?.tier_id || DEFAULT_USAGE_SETTINGS.tiers.free.tier_id,
        display_name: raw.usage_settings.tiers?.free?.display_name || DEFAULT_USAGE_SETTINGS.tiers.free.display_name,
        description: raw.usage_settings.tiers?.free?.description || DEFAULT_USAGE_SETTINGS.tiers.free.description,
        price_ngn: typeof raw.usage_settings.tiers?.free?.price_ngn === 'number' ? raw.usage_settings.tiers.free.price_ngn : DEFAULT_USAGE_SETTINGS.tiers.free.price_ngn,
        credit_allocation: typeof raw.usage_settings.tiers?.free?.credit_allocation === 'number' ? raw.usage_settings.tiers.free.credit_allocation : DEFAULT_USAGE_SETTINGS.tiers.free.credit_allocation,
        max_saved_courses: typeof raw.usage_settings.tiers?.free?.max_saved_courses === 'number' ? raw.usage_settings.tiers.free.max_saved_courses : DEFAULT_USAGE_SETTINGS.tiers.free.max_saved_courses,
        has_verification_badge: typeof raw.usage_settings.tiers?.free?.has_verification_badge === 'boolean' ? raw.usage_settings.tiers.free.has_verification_badge : DEFAULT_USAGE_SETTINGS.tiers.free.has_verification_badge,
        badge_color: raw.usage_settings.tiers?.free?.badge_color || DEFAULT_USAGE_SETTINGS.tiers.free.badge_color,
      },
      basic: {
        tier_id: raw.usage_settings.tiers?.basic?.tier_id || DEFAULT_USAGE_SETTINGS.tiers.basic.tier_id,
        display_name: raw.usage_settings.tiers?.basic?.display_name || DEFAULT_USAGE_SETTINGS.tiers.basic.display_name,
        description: raw.usage_settings.tiers?.basic?.description || DEFAULT_USAGE_SETTINGS.tiers.basic.description,
        price_ngn: typeof raw.usage_settings.tiers?.basic?.price_ngn === 'number' ? raw.usage_settings.tiers.basic.price_ngn : DEFAULT_USAGE_SETTINGS.tiers.basic.price_ngn,
        credit_allocation: typeof raw.usage_settings.tiers?.basic?.credit_allocation === 'number' ? raw.usage_settings.tiers.basic.credit_allocation : DEFAULT_USAGE_SETTINGS.tiers.basic.credit_allocation,
        max_saved_courses: typeof raw.usage_settings.tiers?.basic?.max_saved_courses === 'number' ? raw.usage_settings.tiers.basic.max_saved_courses : DEFAULT_USAGE_SETTINGS.tiers.basic.max_saved_courses,
        has_verification_badge: typeof raw.usage_settings.tiers?.basic?.has_verification_badge === 'boolean' ? raw.usage_settings.tiers.basic.has_verification_badge : DEFAULT_USAGE_SETTINGS.tiers.basic.has_verification_badge,
        badge_color: raw.usage_settings.tiers?.basic?.badge_color || DEFAULT_USAGE_SETTINGS.tiers.basic.badge_color,
      },
      premium: {
        tier_id: raw.usage_settings.tiers?.premium?.tier_id || DEFAULT_USAGE_SETTINGS.tiers.premium.tier_id,
        display_name: raw.usage_settings.tiers?.premium?.display_name || DEFAULT_USAGE_SETTINGS.tiers.premium.display_name,
        description: raw.usage_settings.tiers?.premium?.description || DEFAULT_USAGE_SETTINGS.tiers.premium.description,
        price_ngn: typeof raw.usage_settings.tiers?.premium?.price_ngn === 'number' ? raw.usage_settings.tiers.premium.price_ngn : DEFAULT_USAGE_SETTINGS.tiers.premium.price_ngn,
        credit_allocation: typeof raw.usage_settings.tiers?.premium?.credit_allocation === 'number' ? raw.usage_settings.tiers.premium.credit_allocation : DEFAULT_USAGE_SETTINGS.tiers.premium.credit_allocation,
        max_saved_courses: typeof raw.usage_settings.tiers?.premium?.max_saved_courses === 'number' ? raw.usage_settings.tiers.premium.max_saved_courses : DEFAULT_USAGE_SETTINGS.tiers.premium.max_saved_courses,
        has_verification_badge: typeof raw.usage_settings.tiers?.premium?.has_verification_badge === 'boolean' ? raw.usage_settings.tiers.premium.has_verification_badge : DEFAULT_USAGE_SETTINGS.tiers.premium.has_verification_badge,
        badge_color: raw.usage_settings.tiers?.premium?.badge_color || DEFAULT_USAGE_SETTINGS.tiers.premium.badge_color,
      }
    },
    additional_prices: {
      visual_messages_price: typeof raw.usage_settings.additional_prices?.visual_messages_price === 'number' ? raw.usage_settings.additional_prices.visual_messages_price : DEFAULT_USAGE_SETTINGS.additional_prices.visual_messages_price,
      visual_messages_count: typeof raw.usage_settings.additional_prices?.visual_messages_count === 'number' ? raw.usage_settings.additional_prices.visual_messages_count : DEFAULT_USAGE_SETTINGS.additional_prices.visual_messages_count,
      studyguide_course_price: typeof raw.usage_settings.additional_prices?.studyguide_course_price === 'number' ? raw.usage_settings.additional_prices.studyguide_course_price : DEFAULT_USAGE_SETTINGS.additional_prices.studyguide_course_price,
      studyguide_request_price: typeof raw.usage_settings.additional_prices?.studyguide_request_price === 'number' ? raw.usage_settings.additional_prices.studyguide_request_price : DEFAULT_USAGE_SETTINGS.additional_prices.studyguide_request_price,
    }
  } : (DEFAULT_USAGE_SETTINGS as any),
});
