name: Generate and Save Keystore Secrets

# Only runs when you manually click a button, never automatically
on: workflow_dispatch 

jobs:
  generate-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Keystore
        run: |
          # Generates a keystore with automated inputs
          keytool -genkey -v -keystore release.keystore -alias avelut_alias -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Avelut, OU=Development, O=Avelut Ltd, L=Effurun, S=Delta, C=NG" -storepass "super_secure_password123" -keypass "super_secure_password123"
          
      - name: Convert to Base64
        # -w 0 ensures the base64 string is one continuous line
        run: base64 -w 0 release.keystore > keystore_b64.txt 

      - name: Upload to GitHub Secrets
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }} # Uses your Personal Access Token
        run: |
          # Uses the GitHub CLI to automatically create your repository secrets
          gh secret set ANDROID_KEYSTORE_BASE64 < keystore_b64.txt
          gh secret set KEYSTORE_PASSWORD -b "super_secure_password123"
          gh secret set KEY_ALIAS -b "avelut_alias"
          gh secret set KEY_PASSWORD -b "super_secure_password123"
          
      - name: Cleanup
        run: rm release.keystore keystore_b64.txt
